import React,{useState,useEffect,useRef} from 'react';
import {createRoot} from 'react-dom/client';
import {AgGridReact} from 'ag-grid-react';
import {ModuleRegistry,AllCommunityModule,themeQuartz} from 'ag-grid-community';
ModuleRegistry.registerModules([AllCommunityModule]);
export const windows=[{id:'students',title:'学生资料'}];
function Students({context}){const [rows,setRows]=useState([]),[q,setQ]=useState(''),[query,setQuery]=useState(''),[page,setPage]=useState(1),[total,setTotal]=useState(0),[busy,setBusy]=useState(false),[error,setError]=useState(''),[detail,setDetail]=useState(null),[refresh,setRefresh]=useState(0);const epoch=useRef(0),selection=useRef(0);
useEffect(()=>{const n=++epoch.current;let active=true;setBusy(true);setError('');setRows([]);context.invoke('education.students.read',{page,q:query}).then(d=>{if(!active||n!==epoch.current)return;if(!d?.ok||!Array.isArray(d.records))throw Error();setRows(d.records);setTotal(d.total);}).catch(()=>{if(active)setError('读取失败：请检查学生服务凭证，未回退旧数据。')}).finally(()=>{if(active)setBusy(false)});return()=>{active=false}},[page,query,refresh]);
useEffect(()=>()=>{selection.current++},[]);
async function select(id){const n=++selection.current;setDetail(null);try{const d=await context.invoke('education.student.read',{id});if(n!==selection.current)return;if(!d?.record)throw Error();setDetail(d.record)}catch{if(n===selection.current)setError('所选学生读取失败，请重试')}}
return <section className="ur-student-library"><h2>学生资料库</h2><p>Word／AI 导入资料 · 与浏览器插件共用一份数据</p><form onSubmit={e=>{e.preventDefault();setPage(1);setQuery(q.trim());setRefresh(x=>x+1)}}><input aria-label="搜索学生姓名或编号" placeholder="姓名或编号" value={q} maxLength={160} onChange={e=>setQ(e.target.value)}/><button disabled={busy}>搜索</button><button type="button" disabled={busy} onClick={()=>setRefresh(x=>x+1)}>刷新</button></form>{error&&<p role="alert">{error}</p>}<p role="status">{busy?'正在读取…':'共 '+total+' 位学生'}</p><div style={{height:350}}><AgGridReact theme={themeQuartz} rowData={rows} columnDefs={[{field:'name',headerName:'学生',flex:2,minWidth:160},{field:'id',headerName:'编号',flex:2,minWidth:150},{field:'updatedAt',headerName:'更新时间',flex:1,minWidth:180}]} defaultColDef={{sortable:false,resizable:true}} getRowId={p=>p.data.id} onRowClicked={e=>select(e.data.id)} onCellKeyDown={e=>{if(e.event.key==='Enter')select(e.data.id)}}/></div><footer><button disabled={busy||page<=1} onClick={()=>setPage(p=>p-1)}>上一页</button><span>第 {page} / {Math.max(1,Math.ceil(total/20))} 页 · 每页20位</span><button disabled={busy||page*20>=total} onClick={()=>setPage(p=>p+1)}>下一页</button></footer>{detail&&<details open><summary>{detail.name} · 版本 {detail.version}</summary><p>完整资料只在选择后读取；此处只读。</p><pre>{JSON.stringify(JSON.parse(detail.raw),null,2)}</pre></details>}</section>}
export function mount(root,context){if(context.props?.window&&context.props.window!=='students')throw Error('unknown_window');const style=document.createElement('style');style.textContent='.ur-student-library{font:14px system-ui;padding:16px;color:var(--text-primary,#ddd)}.ur-student-library form,.ur-student-library footer{display:flex;gap:8px;flex-wrap:wrap;margin:12px 0;align-items:center}.ur-student-library input{min-width:140px;flex:1}.ur-student-library input,.ur-student-library button{padding:8px;border:1px solid #687585;border-radius:6px}.ur-student-library pre{white-space:pre-wrap;overflow-wrap:anywhere;max-height:350px;overflow:auto}.ur-student-library [role=alert]{color:#e58d75}';root.append(style);const host=document.createElement('div');root.append(host);const app=createRoot(host);app.render(<Students context={context}/>);return()=>{app.unmount();host.remove();style.remove()}}
