import React,{useState,useEffect,useRef} from 'react';
import {createRoot} from 'react-dom/client';
import {AgGridReact} from 'ag-grid-react';
import {ModuleRegistry,AllCommunityModule,themeQuartz} from 'ag-grid-community';
ModuleRegistry.registerModules([AllCommunityModule]);
const studentTheme=themeQuartz.withParams({backgroundColor:'#292436',foregroundColor:'#ddd8e8',headerBackgroundColor:'#292436',headerTextColor:'#aaa2ba',borderColor:'#443c54',accentColor:'#32dfbe',rowHoverColor:'#303c40',fontFamily:'inherit',fontSize:13,headerFontSize:11,spacing:7,wrapperBorderRadius:8,columnBorder:false});
export const windows=[{id:'students',title:'学生资料'}];
function Students({context}){const [rows,setRows]=useState([]),[q,setQ]=useState(''),[query,setQuery]=useState(''),[page,setPage]=useState(1),[total,setTotal]=useState(0),[busy,setBusy]=useState(false),[error,setError]=useState(''),[detail,setDetail]=useState(null),[refresh,setRefresh]=useState(0);const epoch=useRef(0),selection=useRef(0);
useEffect(()=>{const n=++epoch.current;let active=true;setBusy(true);setError('');setRows([]);context.invoke('education.students.read',{page,q:query}).then(d=>{if(!active||n!==epoch.current)return;if(!d?.ok||!Array.isArray(d.records))throw Error();setRows(d.records);setTotal(d.total);}).catch(()=>{if(active)setError('读取失败：请检查学生服务凭证，未回退旧数据。')}).finally(()=>{if(active)setBusy(false)});return()=>{active=false}},[page,query,refresh]);
useEffect(()=>()=>{selection.current++},[]);
async function select(id){const n=++selection.current;setDetail(null);try{const d=await context.invoke('education.student.read',{id});if(n!==selection.current)return;if(!d?.record)throw Error();setDetail(d.record)}catch{if(n===selection.current)setError('所选学生读取失败，请重试')}}
return <section className="ur-student-library"><header><div><h2>学生资料库</h2><p className="caption">与浏览器插件共享 · 选择学生查看资料</p></div><span className="count">{total} 位</span></header><form onSubmit={e=>{e.preventDefault();setPage(1);setQuery(q.trim());setRefresh(x=>x+1)}}><input aria-label="搜索学生姓名或编号" placeholder="搜索姓名或学生编号…" value={q} maxLength={160} onChange={e=>setQ(e.target.value)}/><button className="search" disabled={busy}>搜索</button><button type="button" disabled={busy} onClick={()=>setRefresh(x=>x+1)}>刷新</button></form>{error&&<p role="alert">{error}</p>}<p role="status">{busy?'正在读取…':'共 '+total+' 位学生'}</p><div><AgGridReact theme={studentTheme} domLayout="autoHeight" rowHeight={52} headerHeight={36} rowData={rows} columnDefs={[{field:'name',headerName:'学生姓名',flex:2,minWidth:220,cellClass:'student-name',tooltipField:'name'},{field:'id',headerName:'学生编号',flex:2,minWidth:160,cellClass:'student-id',tooltipField:'id'},{field:'updatedAt',headerName:'最近更新',flex:1,minWidth:145,valueFormatter:p=>p.value?new Date(p.value).toLocaleString('zh-CN',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false}):'—'}]} defaultColDef={{sortable:false,resizable:true}} getRowId={p=>p.data.id} onRowClicked={e=>select(e.data.id)} onCellKeyDown={e=>{if(e.event.key==='Enter')select(e.data.id)}}/></div><footer><button disabled={busy||page<=1} onClick={()=>setPage(p=>p-1)}>上一页</button><span>第 {page} / {Math.max(1,Math.ceil(total/20))} 页 · 每页20位</span><button disabled={busy||page*20>=total} onClick={()=>setPage(p=>p+1)}>下一页</button></footer>{detail&&<details open><summary>{detail.name} · 版本 {detail.version}</summary><p>完整资料只在选择后读取；此处只读。</p><pre>{JSON.stringify(JSON.parse(detail.raw),null,2)}</pre></details>}</section>}
export function mount(root,context){if(context.props?.window&&context.props.window!=='students')throw Error('unknown_window');const style=document.createElement('style');style.textContent=".ur-student-library{font:13px/1.5 \"PingFang SC\",\"Segoe UI\",sans-serif;margin:6px;padding:20px;background:#292436;border:1px solid #494055;border-radius:12px;color:#ddd8e8;color-scheme:dark}.ur-student-library header{display:flex;justify-content:space-between;gap:12px}.ur-student-library h2{font-size:15px;font-weight:600;margin:0;color:#e5dfed}.ur-student-library .caption{font-size:11px;color:#aaa1b8;margin:5px 0 0}.ur-student-library .count{align-self:flex-start;color:#35e6c2;background:#284442;border-radius:5px;padding:2px 9px;font-size:12px;white-space:nowrap}.ur-student-library form{display:flex;gap:8px;margin:20px 0 8px;flex-wrap:wrap}.ur-student-library input{flex:1;min-width:150px;background:#221e2d;color:#e7e1ed;border:1px solid #585065;border-radius:7px;padding:8px 11px;font:inherit;outline:none}.ur-student-library input:focus{border-color:#35d6b7}.ur-student-library input::placeholder{color:#91879f}.ur-student-library button{background:#342e40;color:#c5bbd1;border:1px solid #484052;border-radius:6px;padding:7px 12px;font:inherit;cursor:pointer}.ur-student-library button:hover:not(:disabled){border-color:#37d9bb;color:#42e7c6}.ur-student-library button.search{background:#294440;color:#35e6c2;border-color:#34564f}.ur-student-library button:disabled{opacity:.38;cursor:default}.ur-student-library button:focus-visible{outline:2px solid #35e6c2;outline-offset:2px}.ur-student-library [role=status]{font-size:11px;color:#a79db4;margin:12px 0 8px}.ur-student-library .student-name{color:#3ee5c3;font-weight:500}.ur-student-library .student-id{color:#9e94ae;font-size:11px}.ur-student-library .ag-row{cursor:pointer}.ur-student-library .ag-header-cell-resize{opacity:.2}.ur-student-library .ag-center-cols-viewport,.ur-student-library .ag-center-cols-container{min-height:0!important}.ur-student-library footer{display:flex;justify-content:flex-end;align-items:center;gap:12px;flex-wrap:wrap;margin:14px 0 0;color:#9f95ac;font-size:11px}.ur-student-library footer button{padding:4px 9px;font-size:11px}.ur-student-library details{margin-top:18px;padding:14px;border:1px solid #494055;border-radius:8px;background:#241f30}.ur-student-library summary{color:#3ee5c3;cursor:pointer}.ur-student-library pre{font-size:12px;white-space:pre-wrap;overflow-wrap:anywhere;max-height:320px;overflow:auto;color:#bcb3ca}.ur-student-library [role=alert]{color:#f0aa98}@media(max-width:480px){.ur-student-library{padding:13px}.ur-student-library footer{gap:7px}}";root.append(style);const host=document.createElement('div');root.append(host);const app=createRoot(host);app.render(<Students context={context}/>);return()=>{app.unmount();host.remove();style.remove()}}
